# Azure Databricks Build Pipeline
# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.8'
  inputs:
    versionSpec: 3.8

- checkout: self
  persistCredentials: true
  clean: true

- script: git checkout main
  displayName: 'Get Latest Branch'

- script: |
    pip install wheel
    cd $(Build.Repository.LocalPath)/functions
    python3 setup.py sdist bdist_wheel

  displayName: 'Build Python Wheel for Libs'

- script: |
    git diff --name-only --diff-filter=AMR HEAD^1 HEAD | xargs -I '{}' cp --parents -r '{}' $(Build.BinariesDirectory)
    cp -r $(Build.Repository.LocalPath)/analytics/ $(Build.BinariesDirectory)
    cp -r $(Build.Repository.LocalPath)/ingestion/ $(Build.BinariesDirectory)
    cp -r $(Build.Repository.LocalPath)/orchestration/ $(Build.BinariesDirectory)
    cp    $(Build.Repository.LocalPath)/functions/dist/*.whl $(Build.BinariesDirectory)
    cp -r $(Build.Repository.LocalPath)/config/ $(Build.BinariesDirectory)
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'DatabricksBuild'